blank_issues_enabled: false
contact_links:
  - name: 1
    url: https://example.com/
    about: Example link
  - name: 2
    url: https://example.com/
    about: Example link
  - name: 3
    url: https://example.com/
    about: Example link
